# Base image
FROM ubuntu:18.04

# Headless install (otherwise it hangs)
ENV DEBIAN_FRONTEND=noninteractive

# System updates
RUN apt-get update && apt -y install software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt-get update && apt -y install php7.4 php7.4-curl php7.4-mbstring php7.4-xml php7.4-zip unzip postgresql postgresql-contrib

# Install Git (for prod not dev)
#RUN apt-get update && apt-get install -y git
#RUN git clone https://github.com/spraddles/php-api

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/bin/composer

# Copying current local DIR to container image DIR (for dev not prod)
RUN mkdir /php-api-build
COPY . /php-api-build

# Install Composer dependencies
RUN cd /php-api-build && composer update

# Move into container DIR
RUN mkdir /php-api-run && cd /php-api-run

# Post build commands
CMD ["sh", "./php-api-run/batch_file.sh"]